/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RadicaleUsersRouteImport } from './routes/radicale-users'
import { Route as NewRouteImport } from './routes/new'
import { Route as ImportRouteImport } from './routes/import'
import { Route as CarddavConnectionRouteImport } from './routes/carddav-connection'
import { Route as IdRouteImport } from './routes/$id'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRadicaleUsersRouteImport } from './routes/api/radicale-users'
import { Route as ApiContactsRouteImport } from './routes/api/contacts'
import { Route as ApiRadicaleUsersUsernameRouteImport } from './routes/api/radicale-users.$username'
import { Route as ApiContactsMergeRouteImport } from './routes/api/contacts.merge'
import { Route as ApiContactsImportRouteImport } from './routes/api/contacts.import'
import { Route as ApiContactsDeduplicateRouteImport } from './routes/api/contacts.deduplicate'
import { Route as ApiContactsIdRouteImport } from './routes/api/contacts.$id'

const RadicaleUsersRoute = RadicaleUsersRouteImport.update({
  id: '/radicale-users',
  path: '/radicale-users',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CarddavConnectionRoute = CarddavConnectionRouteImport.update({
  id: '/carddav-connection',
  path: '/carddav-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRadicaleUsersRoute = ApiRadicaleUsersRouteImport.update({
  id: '/api/radicale-users',
  path: '/api/radicale-users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsRoute = ApiContactsRouteImport.update({
  id: '/api/contacts',
  path: '/api/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRadicaleUsersUsernameRoute =
  ApiRadicaleUsersUsernameRouteImport.update({
    id: '/$username',
    path: '/$username',
    getParentRoute: () => ApiRadicaleUsersRoute,
  } as any)
const ApiContactsMergeRoute = ApiContactsMergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => ApiContactsRoute,
} as any)
const ApiContactsImportRoute = ApiContactsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ApiContactsRoute,
} as any)
const ApiContactsDeduplicateRoute = ApiContactsDeduplicateRouteImport.update({
  id: '/deduplicate',
  path: '/deduplicate',
  getParentRoute: () => ApiContactsRoute,
} as any)
const ApiContactsIdRoute = ApiContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiContactsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/carddav-connection': typeof CarddavConnectionRoute
  '/import': typeof ImportRoute
  '/new': typeof NewRoute
  '/radicale-users': typeof RadicaleUsersRoute
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/radicale-users': typeof ApiRadicaleUsersRouteWithChildren
  '/api/contacts/$id': typeof ApiContactsIdRoute
  '/api/contacts/deduplicate': typeof ApiContactsDeduplicateRoute
  '/api/contacts/import': typeof ApiContactsImportRoute
  '/api/contacts/merge': typeof ApiContactsMergeRoute
  '/api/radicale-users/$username': typeof ApiRadicaleUsersUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/carddav-connection': typeof CarddavConnectionRoute
  '/import': typeof ImportRoute
  '/new': typeof NewRoute
  '/radicale-users': typeof RadicaleUsersRoute
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/radicale-users': typeof ApiRadicaleUsersRouteWithChildren
  '/api/contacts/$id': typeof ApiContactsIdRoute
  '/api/contacts/deduplicate': typeof ApiContactsDeduplicateRoute
  '/api/contacts/import': typeof ApiContactsImportRoute
  '/api/contacts/merge': typeof ApiContactsMergeRoute
  '/api/radicale-users/$username': typeof ApiRadicaleUsersUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/carddav-connection': typeof CarddavConnectionRoute
  '/import': typeof ImportRoute
  '/new': typeof NewRoute
  '/radicale-users': typeof RadicaleUsersRoute
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/radicale-users': typeof ApiRadicaleUsersRouteWithChildren
  '/api/contacts/$id': typeof ApiContactsIdRoute
  '/api/contacts/deduplicate': typeof ApiContactsDeduplicateRoute
  '/api/contacts/import': typeof ApiContactsImportRoute
  '/api/contacts/merge': typeof ApiContactsMergeRoute
  '/api/radicale-users/$username': typeof ApiRadicaleUsersUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$id'
    | '/carddav-connection'
    | '/import'
    | '/new'
    | '/radicale-users'
    | '/api/contacts'
    | '/api/radicale-users'
    | '/api/contacts/$id'
    | '/api/contacts/deduplicate'
    | '/api/contacts/import'
    | '/api/contacts/merge'
    | '/api/radicale-users/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$id'
    | '/carddav-connection'
    | '/import'
    | '/new'
    | '/radicale-users'
    | '/api/contacts'
    | '/api/radicale-users'
    | '/api/contacts/$id'
    | '/api/contacts/deduplicate'
    | '/api/contacts/import'
    | '/api/contacts/merge'
    | '/api/radicale-users/$username'
  id:
    | '__root__'
    | '/'
    | '/$id'
    | '/carddav-connection'
    | '/import'
    | '/new'
    | '/radicale-users'
    | '/api/contacts'
    | '/api/radicale-users'
    | '/api/contacts/$id'
    | '/api/contacts/deduplicate'
    | '/api/contacts/import'
    | '/api/contacts/merge'
    | '/api/radicale-users/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRoute
  CarddavConnectionRoute: typeof CarddavConnectionRoute
  ImportRoute: typeof ImportRoute
  NewRoute: typeof NewRoute
  RadicaleUsersRoute: typeof RadicaleUsersRoute
  ApiContactsRoute: typeof ApiContactsRouteWithChildren
  ApiRadicaleUsersRoute: typeof ApiRadicaleUsersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/radicale-users': {
      id: '/radicale-users'
      path: '/radicale-users'
      fullPath: '/radicale-users'
      preLoaderRoute: typeof RadicaleUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carddav-connection': {
      id: '/carddav-connection'
      path: '/carddav-connection'
      fullPath: '/carddav-connection'
      preLoaderRoute: typeof CarddavConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/radicale-users': {
      id: '/api/radicale-users'
      path: '/api/radicale-users'
      fullPath: '/api/radicale-users'
      preLoaderRoute: typeof ApiRadicaleUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts': {
      id: '/api/contacts'
      path: '/api/contacts'
      fullPath: '/api/contacts'
      preLoaderRoute: typeof ApiContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/radicale-users/$username': {
      id: '/api/radicale-users/$username'
      path: '/$username'
      fullPath: '/api/radicale-users/$username'
      preLoaderRoute: typeof ApiRadicaleUsersUsernameRouteImport
      parentRoute: typeof ApiRadicaleUsersRoute
    }
    '/api/contacts/merge': {
      id: '/api/contacts/merge'
      path: '/merge'
      fullPath: '/api/contacts/merge'
      preLoaderRoute: typeof ApiContactsMergeRouteImport
      parentRoute: typeof ApiContactsRoute
    }
    '/api/contacts/import': {
      id: '/api/contacts/import'
      path: '/import'
      fullPath: '/api/contacts/import'
      preLoaderRoute: typeof ApiContactsImportRouteImport
      parentRoute: typeof ApiContactsRoute
    }
    '/api/contacts/deduplicate': {
      id: '/api/contacts/deduplicate'
      path: '/deduplicate'
      fullPath: '/api/contacts/deduplicate'
      preLoaderRoute: typeof ApiContactsDeduplicateRouteImport
      parentRoute: typeof ApiContactsRoute
    }
    '/api/contacts/$id': {
      id: '/api/contacts/$id'
      path: '/$id'
      fullPath: '/api/contacts/$id'
      preLoaderRoute: typeof ApiContactsIdRouteImport
      parentRoute: typeof ApiContactsRoute
    }
  }
}

interface ApiContactsRouteChildren {
  ApiContactsIdRoute: typeof ApiContactsIdRoute
  ApiContactsDeduplicateRoute: typeof ApiContactsDeduplicateRoute
  ApiContactsImportRoute: typeof ApiContactsImportRoute
  ApiContactsMergeRoute: typeof ApiContactsMergeRoute
}

const ApiContactsRouteChildren: ApiContactsRouteChildren = {
  ApiContactsIdRoute: ApiContactsIdRoute,
  ApiContactsDeduplicateRoute: ApiContactsDeduplicateRoute,
  ApiContactsImportRoute: ApiContactsImportRoute,
  ApiContactsMergeRoute: ApiContactsMergeRoute,
}

const ApiContactsRouteWithChildren = ApiContactsRoute._addFileChildren(
  ApiContactsRouteChildren,
)

interface ApiRadicaleUsersRouteChildren {
  ApiRadicaleUsersUsernameRoute: typeof ApiRadicaleUsersUsernameRoute
}

const ApiRadicaleUsersRouteChildren: ApiRadicaleUsersRouteChildren = {
  ApiRadicaleUsersUsernameRoute: ApiRadicaleUsersUsernameRoute,
}

const ApiRadicaleUsersRouteWithChildren =
  ApiRadicaleUsersRoute._addFileChildren(ApiRadicaleUsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRoute,
  CarddavConnectionRoute: CarddavConnectionRoute,
  ImportRoute: ImportRoute,
  NewRoute: NewRoute,
  RadicaleUsersRoute: RadicaleUsersRoute,
  ApiContactsRoute: ApiContactsRouteWithChildren,
  ApiRadicaleUsersRoute: ApiRadicaleUsersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
