/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IdRouteImport } from './routes/$id'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiContactsRouteImport } from './routes/api/contacts'
import { Route as ApiContactsImportRouteImport } from './routes/api/contacts.import'
import { Route as ApiContactsDeduplicateRouteImport } from './routes/api/contacts.deduplicate'
import { Route as ApiContactsIdRouteImport } from './routes/api/contacts.$id'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsRoute = ApiContactsRouteImport.update({
  id: '/api/contacts',
  path: '/api/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsImportRoute = ApiContactsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ApiContactsRoute,
} as any)
const ApiContactsDeduplicateRoute = ApiContactsDeduplicateRouteImport.update({
  id: '/deduplicate',
  path: '/deduplicate',
  getParentRoute: () => ApiContactsRoute,
} as any)
const ApiContactsIdRoute = ApiContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiContactsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/new': typeof NewRoute
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/contacts/$id': typeof ApiContactsIdRoute
  '/api/contacts/deduplicate': typeof ApiContactsDeduplicateRoute
  '/api/contacts/import': typeof ApiContactsImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/new': typeof NewRoute
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/contacts/$id': typeof ApiContactsIdRoute
  '/api/contacts/deduplicate': typeof ApiContactsDeduplicateRoute
  '/api/contacts/import': typeof ApiContactsImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/new': typeof NewRoute
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/contacts/$id': typeof ApiContactsIdRoute
  '/api/contacts/deduplicate': typeof ApiContactsDeduplicateRoute
  '/api/contacts/import': typeof ApiContactsImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$id'
    | '/new'
    | '/api/contacts'
    | '/api/contacts/$id'
    | '/api/contacts/deduplicate'
    | '/api/contacts/import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$id'
    | '/new'
    | '/api/contacts'
    | '/api/contacts/$id'
    | '/api/contacts/deduplicate'
    | '/api/contacts/import'
  id:
    | '__root__'
    | '/'
    | '/$id'
    | '/new'
    | '/api/contacts'
    | '/api/contacts/$id'
    | '/api/contacts/deduplicate'
    | '/api/contacts/import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRoute
  NewRoute: typeof NewRoute
  ApiContactsRoute: typeof ApiContactsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts': {
      id: '/api/contacts'
      path: '/api/contacts'
      fullPath: '/api/contacts'
      preLoaderRoute: typeof ApiContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts/import': {
      id: '/api/contacts/import'
      path: '/import'
      fullPath: '/api/contacts/import'
      preLoaderRoute: typeof ApiContactsImportRouteImport
      parentRoute: typeof ApiContactsRoute
    }
    '/api/contacts/deduplicate': {
      id: '/api/contacts/deduplicate'
      path: '/deduplicate'
      fullPath: '/api/contacts/deduplicate'
      preLoaderRoute: typeof ApiContactsDeduplicateRouteImport
      parentRoute: typeof ApiContactsRoute
    }
    '/api/contacts/$id': {
      id: '/api/contacts/$id'
      path: '/$id'
      fullPath: '/api/contacts/$id'
      preLoaderRoute: typeof ApiContactsIdRouteImport
      parentRoute: typeof ApiContactsRoute
    }
  }
}

interface ApiContactsRouteChildren {
  ApiContactsIdRoute: typeof ApiContactsIdRoute
  ApiContactsDeduplicateRoute: typeof ApiContactsDeduplicateRoute
  ApiContactsImportRoute: typeof ApiContactsImportRoute
}

const ApiContactsRouteChildren: ApiContactsRouteChildren = {
  ApiContactsIdRoute: ApiContactsIdRoute,
  ApiContactsDeduplicateRoute: ApiContactsDeduplicateRoute,
  ApiContactsImportRoute: ApiContactsImportRoute,
}

const ApiContactsRouteWithChildren = ApiContactsRoute._addFileChildren(
  ApiContactsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRoute,
  NewRoute: NewRoute,
  ApiContactsRoute: ApiContactsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
