/**
 * Option data for address dropdowns (country and US state).
 */

export interface AddressOption {
	value: string
	label: string
}

export const DEFAULT_COUNTRY = 'United States'

/** True when the value names the United States in any common spelling. */
export function isUnitedStates(country: string): boolean {
	const normalized = country.toLowerCase().replace(/[.\s]/g, '').trim()
	return ['us', 'usa', 'unitedstates', 'unitedstatesofamerica', 'america'].includes(normalized)
}

/** US states, DC, and territories. Values are the conventional two-letter codes. */
export const US_STATES: Array<AddressOption> = [
	{ value: 'AL', label: 'Alabama (AL)' },
	{ value: 'AK', label: 'Alaska (AK)' },
	{ value: 'AZ', label: 'Arizona (AZ)' },
	{ value: 'AR', label: 'Arkansas (AR)' },
	{ value: 'CA', label: 'California (CA)' },
	{ value: 'CO', label: 'Colorado (CO)' },
	{ value: 'CT', label: 'Connecticut (CT)' },
	{ value: 'DE', label: 'Delaware (DE)' },
	{ value: 'DC', label: 'District of Columbia (DC)' },
	{ value: 'FL', label: 'Florida (FL)' },
	{ value: 'GA', label: 'Georgia (GA)' },
	{ value: 'HI', label: 'Hawaii (HI)' },
	{ value: 'ID', label: 'Idaho (ID)' },
	{ value: 'IL', label: 'Illinois (IL)' },
	{ value: 'IN', label: 'Indiana (IN)' },
	{ value: 'IA', label: 'Iowa (IA)' },
	{ value: 'KS', label: 'Kansas (KS)' },
	{ value: 'KY', label: 'Kentucky (KY)' },
	{ value: 'LA', label: 'Louisiana (LA)' },
	{ value: 'ME', label: 'Maine (ME)' },
	{ value: 'MD', label: 'Maryland (MD)' },
	{ value: 'MA', label: 'Massachusetts (MA)' },
	{ value: 'MI', label: 'Michigan (MI)' },
	{ value: 'MN', label: 'Minnesota (MN)' },
	{ value: 'MS', label: 'Mississippi (MS)' },
	{ value: 'MO', label: 'Missouri (MO)' },
	{ value: 'MT', label: 'Montana (MT)' },
	{ value: 'NE', label: 'Nebraska (NE)' },
	{ value: 'NV', label: 'Nevada (NV)' },
	{ value: 'NH', label: 'New Hampshire (NH)' },
	{ value: 'NJ', label: 'New Jersey (NJ)' },
	{ value: 'NM', label: 'New Mexico (NM)' },
	{ value: 'NY', label: 'New York (NY)' },
	{ value: 'NC', label: 'North Carolina (NC)' },
	{ value: 'ND', label: 'North Dakota (ND)' },
	{ value: 'OH', label: 'Ohio (OH)' },
	{ value: 'OK', label: 'Oklahoma (OK)' },
	{ value: 'OR', label: 'Oregon (OR)' },
	{ value: 'PA', label: 'Pennsylvania (PA)' },
	{ value: 'RI', label: 'Rhode Island (RI)' },
	{ value: 'SC', label: 'South Carolina (SC)' },
	{ value: 'SD', label: 'South Dakota (SD)' },
	{ value: 'TN', label: 'Tennessee (TN)' },
	{ value: 'TX', label: 'Texas (TX)' },
	{ value: 'UT', label: 'Utah (UT)' },
	{ value: 'VT', label: 'Vermont (VT)' },
	{ value: 'VA', label: 'Virginia (VA)' },
	{ value: 'WA', label: 'Washington (WA)' },
	{ value: 'WV', label: 'West Virginia (WV)' },
	{ value: 'WI', label: 'Wisconsin (WI)' },
	{ value: 'WY', label: 'Wyoming (WY)' },
	{ value: 'AS', label: 'American Samoa (AS)' },
	{ value: 'GU', label: 'Guam (GU)' },
	{ value: 'MP', label: 'Northern Mariana Islands (MP)' },
	{ value: 'PR', label: 'Puerto Rico (PR)' },
	{ value: 'VI', label: 'U.S. Virgin Islands (VI)' },
]

/** Country display names, United States first, then alphabetical. */
export const COUNTRIES: Array<string> = [
	'United States',
	'Afghanistan',
	'Albania',
	'Algeria',
	'Andorra',
	'Angola',
	'Antigua and Barbuda',
	'Argentina',
	'Armenia',
	'Australia',
	'Austria',
	'Azerbaijan',
	'Bahamas',
	'Bahrain',
	'Bangladesh',
	'Barbados',
	'Belarus',
	'Belgium',
	'Belize',
	'Benin',
	'Bhutan',
	'Bolivia',
	'Bosnia and Herzegovina',
	'Botswana',
	'Brazil',
	'Brunei',
	'Bulgaria',
	'Burkina Faso',
	'Burundi',
	'Cabo Verde',
	'Cambodia',
	'Cameroon',
	'Canada',
	'Central African Republic',
	'Chad',
	'Chile',
	'China',
	'Colombia',
	'Comoros',
	'Congo',
	'Costa Rica',
	'Croatia',
	'Cuba',
	'Cyprus',
	'Czechia',
	'Democratic Republic of the Congo',
	'Denmark',
	'Djibouti',
	'Dominica',
	'Dominican Republic',
	'Ecuador',
	'Egypt',
	'El Salvador',
	'Equatorial Guinea',
	'Eritrea',
	'Estonia',
	'Eswatini',
	'Ethiopia',
	'Fiji',
	'Finland',
	'France',
	'Gabon',
	'Gambia',
	'Georgia',
	'Germany',
	'Ghana',
	'Greece',
	'Grenada',
	'Guatemala',
	'Guinea',
	'Guinea-Bissau',
	'Guyana',
	'Haiti',
	'Honduras',
	'Hungary',
	'Iceland',
	'India',
	'Indonesia',
	'Iran',
	'Iraq',
	'Ireland',
	'Israel',
	'Italy',
	'Ivory Coast',
	'Jamaica',
	'Japan',
	'Jordan',
	'Kazakhstan',
	'Kenya',
	'Kiribati',
	'Kosovo',
	'Kuwait',
	'Kyrgyzstan',
	'Laos',
	'Latvia',
	'Lebanon',
	'Lesotho',
	'Liberia',
	'Libya',
	'Liechtenstein',
	'Lithuania',
	'Luxembourg',
	'Madagascar',
	'Malawi',
	'Malaysia',
	'Maldives',
	'Mali',
	'Malta',
	'Marshall Islands',
	'Mauritania',
	'Mauritius',
	'Mexico',
	'Micronesia',
	'Moldova',
	'Monaco',
	'Mongolia',
	'Montenegro',
	'Morocco',
	'Mozambique',
	'Myanmar',
	'Namibia',
	'Nauru',
	'Nepal',
	'Netherlands',
	'New Zealand',
	'Nicaragua',
	'Niger',
	'Nigeria',
	'North Korea',
	'North Macedonia',
	'Norway',
	'Oman',
	'Pakistan',
	'Palau',
	'Palestine',
	'Panama',
	'Papua New Guinea',
	'Paraguay',
	'Peru',
	'Philippines',
	'Poland',
	'Portugal',
	'Qatar',
	'Romania',
	'Russia',
	'Rwanda',
	'Saint Kitts and Nevis',
	'Saint Lucia',
	'Saint Vincent and the Grenadines',
	'Samoa',
	'San Marino',
	'Sao Tome and Principe',
	'Saudi Arabia',
	'Senegal',
	'Serbia',
	'Seychelles',
	'Sierra Leone',
	'Singapore',
	'Slovakia',
	'Slovenia',
	'Solomon Islands',
	'Somalia',
	'South Africa',
	'South Korea',
	'South Sudan',
	'Spain',
	'Sri Lanka',
	'Sudan',
	'Suriname',
	'Sweden',
	'Switzerland',
	'Syria',
	'Taiwan',
	'Tajikistan',
	'Tanzania',
	'Thailand',
	'Timor-Leste',
	'Togo',
	'Tonga',
	'Trinidad and Tobago',
	'Tunisia',
	'Turkey',
	'Turkmenistan',
	'Tuvalu',
	'Uganda',
	'Ukraine',
	'United Arab Emirates',
	'United Kingdom',
	'Uruguay',
	'Uzbekistan',
	'Vanuatu',
	'Vatican City',
	'Venezuela',
	'Vietnam',
	'Yemen',
	'Zambia',
	'Zimbabwe',
]
